"""empty message

Revision ID: 22417a6b0656
Revises: 43a1ba9617fc
Create Date: 2021-01-08 20:11:58.029861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22417a6b0656'
down_revision = '43a1ba9617fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videoscramble', sa.Column('video_filename', sa.String(length=200), nullable=True))
    op.drop_column('videoscramble', 'video_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videoscramble', sa.Column('video_path', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('videoscramble', 'video_filename')
    # ### end Alembic commands ###
