"""empty message

Revision ID: 43a1ba9617fc
Revises: e94d563a2497
Create Date: 2021-01-08 20:03:01.658506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a1ba9617fc'
down_revision = 'e94d563a2497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videoscramble', sa.Column('video_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videoscramble', 'video_path')
    # ### end Alembic commands ###
